CREATE TABLE T_ORDER (
         ID              NUMBER(19) PRIMARY KEY,
         USER_ID         VARCHAR2(64),
         ORDER_QUANTITY  DECIMAL(20, 2) NOT NULL,
         BUY_SELL        VARCHAR2(4)
);

CREATE SEQUENCE SEQ_ORDER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;